[Interface]
PrivateKey = ENgBWOi60/u1wavpzizferQSR2SvXrOR9fs31HWBr3o=
Address = 10.2.0.4/32
DNS = 1.1.1.1

[Peer]
PublicKey = 3hulKeSLVSL+ftOb/rVAvQb6Q8+d8ZW0IWSqm0o94zo=
Endpoint = germany-server.vpnprovider.com:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25